web/src/components/node/ReactFlowWrapper.tsx, web/src/stores/NodeStore.ts
- block multiple connections to the same input handle
- enforce validation when reconnecting edges
- expose validation to ReactFlow via `isValidConnection`
- remove `ignoreEdgeId` option from `validateConnection`
- `npm test` *(fails: jest not found)*
- `npm run lint` *(fails: cannot find @eslint/compat)*
- `npm run typecheck` *(fails: missing dependencies)*
=> Prevent multiple edges per input

web/src/components/node/OutputRenderer.tsx
- avoid rendering `OutputRenderer` when there's no output
- only show Copy button when there's data to copy
- `npm test --silent` *(fails: jest not found)*
=> Fix empty output rendering

web/src/stores/AssetStore.ts
- invalidate folder list query when creating a folder so FolderProperty updates
- `npm run lint` *(fails: React hook order errors)*
- `npm run typecheck` *(fails: cannot find modules / TS errors)*
=> Fix FolderProperty refresh after folder creation

electron/eslint.config.mjs, electron/src/__tests__/window.test.ts, web/src/components/node/OutputRenderer.tsx, web/src/hooks/handlers/useDropHandler.ts
- ignore `jest.config.ts` during linting
- avoid using `require` in tests
- ensure hooks run consistently in `OutputRenderer`
- clean up dependencies array in `useDropHandler`
- `npm run lint` in web
=> Fix eslint issues

web/src/stores/__tests__/ModelDownloadStore.test.ts
- add unit tests for ModelDownloadStore
- `npm run lint` in `apps` *(fails: Cannot find package '@eslint/compat')*
- `npm run typecheck` in `apps` *(fails: missing @types packages)*
=> Add tests for ModelDownloadStore

web/src/stores/__tests__/WorkflowChatStore.test.ts
- add unit tests for WorkflowChatStore
- `npm test`
- `npm run lint` in apps *(fails: Cannot find package '@eslint/compat')*
- `npm run typecheck` in apps *(fails: cannot find types)*
=> Add WorkflowChatStore tests

electron/src/__tests__/settings.test.ts
- add integration tests for Electron settings utilities
- `npm test`
=> Add tests for settings module

electron/src/__tests__/workflowExecution.test.ts
- test workflow execution logic for headless and normal modes
- `cd electron && npm run lint`
- `npm test`
=> Add tests for workflowExecution

electron/src/__tests__/workflowRunner.test.ts
- test WorkflowRunner zustand store
- `npm run lint --prefix electron`
- `npm run typecheck --prefix electron`
- `npm test --prefix electron`
=> Add WorkflowRunner tests

apps/README.md, docs/README.md, electron/README.md, examples/README.md, scripts/README.md, web/README.md, workflow_runner/README.md
- document the purpose of top-level directories with new README files
- `npm run lint` in `apps` *(fails: cannot find module `@eslint/compat`)*
- `npm run typecheck` in `apps` *(fails: missing type definitions)*
- `npm test` in `apps` *(fails: jest not found)*
=> Add folder READMEs

web/src/components/__tests__/ProtectedRoute.test.tsx, web/src/stores/__tests__/PanelStore.test.ts, web/src/stores/__tests__/SettingsStore.test.ts
- add tests for panel state store
- add tests for settings store
- add tests for `ProtectedRoute` component
- fix type errors in AssetRef components
=> Add additional unit tests

.github/workflows/hugo.yml, README.md, docs/README.md, docs/content/en/_index.md, docs/content/en/docs/_index.md, docs/content/en/docs/getting-started.md, docs/hugo.toml
- add a basic Hugo site under `docs/` configured with the Docsy theme
- document local docs development in `docs/README.md`
- add GitHub Actions workflow to build and deploy docs to Pages
- mention documentation site in main README
- `npm run lint` / `npm run typecheck` / `npm test` in `web`
- `npm run lint` / `npm run typecheck` / `npm test` in `electron`
- `npm run lint` / `npm run typecheck` / `npm test` in `apps`
=> Add Hugo docs skeleton and GitHub Pages workflow

.github/workflows/conda.yaml, .github/workflows/docker-publish.yaml, .github/workflows/hugo.yml, .github/workflows/release.yaml, .github/workflows/test.yml
- update checkout to v4 in all workflows
- bump configure-pages to v4
- bump upload-pages-artifact to v3
- `npm run lint` in web
- `npm run typecheck` in web
- `npm test` in web
=> Upgrade GitHub Actions versions

docs/content/en/_index.md
- expand docs index page with overview and features of NodeTool
=> Update docs index

docs/content/en/docs/installation.md
- add new documentation page describing the installation steps
- `npm test` in `apps`
=> Add user guide for first-time installation

apps/jest.setup.ts, apps/src/__tests__/stores/ChatStore.test.ts
- increase test coverage for apps by adding new tests for ChatStore
- polyfill TextEncoder/TextDecoder for jest in apps
- `npm test` in apps
- `npm run lint` in web
- `npm run typecheck` in web
- `npm test` in web
=> Add ChatStore tests

web/src/utils/__tests__/createAssetFile.test.ts, web/src/utils/__tests__/formatDateAndTime.test.ts, web/src/utils/__tests__/getFileExtension.test.ts
- increase test coverage in web utils
- test createAssetFile utility
- test date & time formatting helpers
- test getFileExtension helper
- `npm test`
=> Add tests for web utils

web/src/contexts/NodeContext.tsx, web/src/hooks/useCreateNode.ts, web/src/providers/MenuProvider.tsx
- document functionality in `useCreateNode` hook
- add context explanation in `NodeContext`
- clarify `MenuProvider` usage
- `cd web && npm run lint`
- `npm test`
- `cd ../apps && npm run lint`
- `npm test`
=> Add comments for clarity in React hooks and providers

build.py, scripts/changelog.py, scripts/release.py, web/llm_lint.py
- document Build class and helper functions in `build.py`
- add docstrings in `scripts/changelog.py`
- add docstrings in `scripts/release.py`
- document helper methods in `web/llm_lint.py`
=> Add docstrings for scripts

electron/src/__tests__/window.test.ts, electron/src/__tests__/workflowWindow.test.ts
- cover edge cases in forceQuit
- add workflowWindow tests
- `cd electron && npm run lint`
- `cd electron && npm run typecheck`
- `cd electron && npm test`
- `cd electron && npm run test:coverage`
=> Improve electron test coverage

web/src/utils/__tests__/browser.test.ts, web/src/utils/__tests__/titleizeString.test.ts
- improve test coverage for web utilities
- test `titleizeString` for text formatting
- test `getIsElectronDetails` for environment detection
- `npm --prefix web run lint`
- `npm --prefix web run typecheck`
- `npm --prefix web test`
=> Add utility tests

web/jest.config.ts, web/src/components/node_menu/RenderNamespaces.tsx, web/src/lib/supabaseClient.ts, web/src/stores/__tests__/WorkflowChatStore.test.ts
- replace `process.env` usage with `import.meta.env`
- adjust jest config to support ESM
- mock Supabase client in `WorkflowChatStore` test
- `npm run lint` in `apps` *(fails: `no-require-imports`)*
=> Use import.meta.env in web

apps/jest.setup.ts
- use ES module import in `apps/jest.setup.ts`
- `npm run lint` in web
- `npm run typecheck` in web
- `npm test` in web
=> Fix ESLint error in apps

.github/workflows/hugo.yml
- install Docsy theme in CI before building the docs
- `npm test`
- `npm test` in apps
=> Fix Hugo build workflow

web/src/__mocks__/fixtures.ts, web/src/serverState/__tests__/tryCacheFiles.test.ts, web/src/serverState/__tests__/useAsset.test.tsx
- add fixtures for tests
- test tryCacheFiles functions
- test useAsset hook with mock store
- `cd web && npm run lint`
- `npm test`
- `cd ../apps && npm run lint`
- `npm test`
=> Add basic serverState unit tests

web/src/contexts/__tests__/NodeContext.test.tsx
- add initial unit tests for NodeContext provider and hooks
- `npm run lint` in `apps` *(fails: A `require()` style import is forbidden)*
=> Add tests for NodeContext

web/src/providers/__tests__/ConnectableNodesProvider.test.tsx, web/src/providers/__tests__/ContextMenuProvider.test.tsx, web/src/providers/__tests__/MenuProvider.test.tsx
- add unit tests for ConnectableNodesProvider, ContextMenuProvider and MenuProvider
- `npm test`
- `cd ../apps && npm run lint` *(fails: eslint error)*
- `npm test`
=> Add tests for provider components

apps/jest.setup.ts, apps/src/__tests__/stores/ChatStore.test.ts, apps/src/__tests__/stores/WorkflowRunner.test.ts
- add unit tests for ChatStore and WorkflowRunner in `apps`
- polyfill TextEncoder/TextDecoder in Jest setup to allow msgpack usage
- `npm test` in `apps`
- `npm run lint` && `npm run typecheck` && `npm test` in `web`
- `npm run lint` && `npm run typecheck` && `npm test` in `electron`
=> Add store tests for apps

web/src/hooks/assets/__tests__/useAssetSelection.test.ts, web/src/hooks/handlers/useFileDrop.ts
- handle dropped assets in `useFileDrop`
- satisfy lint for tests
- `npm test`
=> Fix asset drag-to-dropzone

apps/src/stores/WorkflowRunner.ts
- update mini-app `WorkflowRunner` to normalize asset outputs like the web runner
- convert base64 asset values to `Uint8Array` and store them with type info
- `npm test` in `apps`
- `npm run lint` in `web` *(fails: A `require()` style import is forbidden)*
=> Align mini-app WorkflowRunner audio handling

web/src/hooks/handlers/useResizePanel.ts, web/src/stores/PanelStore.ts
- collapse panel in store
- handle collapsing in resize hook
- `npm run lint` (fails: A `require()` style import is forbidden)
- `npm test`
=> Fix left panel collapse logic

web/src/components/node_editor/__tests__/Alert.test.tsx, web/src/components/node_editor/__tests__/ConnectionLine.test.tsx, web/src/components/node_editor/__tests__/LoadingAnimation.test.tsx, web/src/components/node_editor/__tests__/NotificationsList.test.tsx
- add tests for Alert, ConnectionLine, LoadingAnimation, and NotificationsList
- `npm test`
=> Add unit tests for node editor components

web/src/styles/nodes.css
- hide advanced fields "Show more" button when zoomed out
- `npm test`
- `cd apps && npm run lint`
- `npm test`
=> Fix show more button visibility

electron/src/__tests__/installer.test.ts
- extend Electron installer tests
- verify `INSTALL_TO_LOCATION` handler registration
- `npm test`
=> Add installer IPC registration test

web/src/components/node/ReactFlowWrapper.tsx, web/src/components/node_editor/EdgeGradientDefinitions.tsx, web/src/components/themes/GenerateCSS.tsx, web/src/config/data_types.tsx, web/src/hooks/useProcessedEdges.ts
Refactor: Optimized Edge Styling with Dynamic Type-Based Colors and On-Demand Gradients
**Dynamic Edges**: 
Edges are now styled with a solid color for same-type connections or a linear gradient for different-type connections, based on the handle data types.
On-demand SVG gradient generation: creating gradients only as needed by active edges. 
Improved Load Behavior: Corrected an issue where edges did not receive proper type-based styling upon initial workflow load.
Code Centralization: Edge styling logic is now consolidated within a new useProcessedEdges hook, and redundant CSS for edge coloring has been removed.
=> Hd edges with gradients

web/src/stores/NodeStore.ts, web/src/stores/__tests__/NodeStore.test.ts, web/src/stores/graphEdgeToReactFlowEdge.ts
fixes constant warnings from reactflow if edge input or output is not found.
hook.js:608 [React Flow]: Couldn't create edge for source handle id: "output", edge id: 7b4eff36-a9c7-476c-bb33-717862f49b50. Help: https://reactflow.dev/error#008
refactored sanitize functions.
=> Fix reactflow warning about missing edges

web/src/utils/__tests__/ColorUtils.test.ts, web/src/utils/__tests__/binary.test.ts, web/src/utils/__tests__/highlightText.test.ts
- add tests for ColorUtils
- add tests for binary utility
- relax timing assertion in highlightText test
- `npm test`
- `cd apps && npm run lint`
- `npm test`
=> Increase test coverage

web/src/components/workflows/ExampleGrid.tsx, web/src/config/constants.ts, web/src/contexts/WorkflowManagerContext.tsx, web/src/types/search.ts, web/src/utils/findMatchingNodesInWorkflows.ts, web/src/utils/nodeDisplay.ts, web/src/utils/workflowSearch.ts
searching examples by nodes was broken.
- fixed and removed old code
- improved style
also see PR in nodetool-core
=> HD fix example search by nodes

web/src/stores/__tests__/GlobalChatStore.test.ts, web/src/utils/formatDateAndTime.ts
- add Jest tests for GlobalChatStore
- `npm --prefix web run lint`
- `npm --prefix web run typecheck`
- `npm --prefix web test`
- `npm --prefix apps run lint`
- `npm --prefix apps run typecheck`
- `npm --prefix apps test`
- `npm --prefix electron run lint`
- `npm --prefix electron run typecheck`
- `npm --prefix electron test`
=> Add GlobalChatStore unit tests
